# Site settings
title: OD的博客
#email: suyan0830@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  OD的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://laosijikaichele.github.io # the base hostname & protocol for your site
#rss_url: /pages/feed.xml
author: OD

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: jasontakeiteasy
#weibo: 
github: laosijikaichele
#instagram: 
#linkedin: 

# avatar and Favicon
avatar: https://github.com/laosijikaichele/img-repo/blob/master/29225782.jpeg
favicon: https://github.com/laosijikaichele/img-repo/blob/master/29225782%20(2).jpeg

# disqus config
disqus:
  shortname: OD

# google analytics config
#ga:
#  id: 
#  url: 

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-feed

